version: "3"
services:
  nginx:
    ports:
      - 80:80
  app:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER} 
      - MONGO_PASS=${MONGO_PASS}
      - SESSION_SECRET=${SESSION_SECRET}
      - MONGO_PORT=${MONGO_PORT}
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}