version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  app:
    build: .
    image: btdtech/node-app
    env_file:
      - ./.env
    depends_on:
      - mongo
      - nginx
      - redis
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis:latest
volumes:
  mongo-db: